export const CITIES = [
  'Brazzaville',
  'Pointe-Noire',
  'Dolisie',
  'Nkayi',
  'Ouesso',
  'Impfondo',
  'Owando',
  'Madingou',
  'Sibiti',
  'Kinkala',
] as const;

export type City = typeof CITIES[number];

export const CATEGORIES = [
  { name: 'Immobilier', slug: 'immobilier', icon: 'Home', color: '#E8F5ED', count: 3420 },
  { name: 'Véhicules', slug: 'vehicules', icon: 'Car', color: '#FFF3E0', count: 1850 },
  { name: 'Emploi', slug: 'emploi', icon: 'Briefcase', color: '#E3F2FD', count: 2100 },
  { name: 'Services', slug: 'services', icon: 'Wrench', color: '#F3E5F5', count: 980 },
  { name: 'Électronique', slug: 'electronique', icon: 'Smartphone', color: '#E0F7FA', count: 1540 },
  { name: 'Mode & Beauté', slug: 'mode-beaute', icon: 'Shirt', color: '#FCE4EC', count: 870 },
  { name: 'Maison & Jardin', slug: 'maison-jardin', icon: 'Sofa', color: '#F1F8E9', count: 620 },
  { name: 'Loisirs', slug: 'loisirs', icon: 'Music', color: '#FFF8E1', count: 340 },
  { name: 'Agriculture', slug: 'agriculture', icon: 'Leaf', color: '#E8F5E9', count: 210 },
  { name: 'Animaux', slug: 'animaux', icon: 'PawPrint', color: '#FBE9E7', count: 180 },
  { name: 'Matériaux BTP', slug: 'materiaux-btp', icon: 'Building', color: '#ECEFF1', count: 290 },
  { name: 'Autres', slug: 'autres', icon: 'Grid3X3', color: '#F5F5F5', count: 150 },
] as const;

export const formatPrice = (price: number): string => {
  return price.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ' ') + ' FCFA';
};

export const MOCK_LISTINGS = [
  {
    id: '1',
    title: 'Appartement 3 pièces meublé — Bacongo',
    price: 350000,
    city: 'Brazzaville',
    neighborhood: 'Bacongo',
    category: 'Immobilier',
    imageUrl: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=400&h=300&fit=crop',
    isSponsored: true,
    sponsorLevel: 'premium' as const,
    createdAt: '2h',
    userName: 'Parfait Mbemba',
    isVerified: true,
    priceNegotiable: true,
  },
  {
    id: '2',
    title: 'Toyota RAV4 2019 — Très bon état',
    price: 12500000,
    city: 'Pointe-Noire',
    neighborhood: 'Centre-ville',
    category: 'Véhicules',
    imageUrl: 'https://images.unsplash.com/photo-1568844293986-8d0400f95e1d?w=400&h=300&fit=crop',
    isSponsored: true,
    sponsorLevel: 'visibility' as const,
    createdAt: '5h',
    userName: 'Auto Congo SARL',
    isVerified: true,
    priceNegotiable: false,
  },
  {
    id: '3',
    title: 'iPhone 14 Pro Max 256GB — Neuf sous emballage',
    price: 850000,
    city: 'Brazzaville',
    neighborhood: 'Poto-Poto',
    category: 'Électronique',
    imageUrl: 'https://images.unsplash.com/photo-1678685888221-cda773a3dcdb?w=400&h=300&fit=crop',
    isSponsored: true,
    sponsorLevel: 'pro' as const,
    createdAt: '1j',
    userName: 'Tech Congo Store',
    isVerified: true,
    priceNegotiable: false,
  },
  {
    id: '4',
    title: 'Cuisinière à gaz 5 feux — NASCO',
    price: 185000,
    city: 'Brazzaville',
    neighborhood: 'Moungali',
    category: 'Maison & Jardin',
    imageUrl: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=300&fit=crop',
    isSponsored: true,
    sponsorLevel: 'visibility' as const,
    createdAt: '3h',
    userName: 'Gloire Okamba',
    isVerified: false,
    priceNegotiable: true,
  },
  {
    id: '5',
    title: 'Terrain 500m² — Kintélé, titre foncier',
    price: 8000000,
    city: 'Brazzaville',
    neighborhood: 'Kintélé',
    category: 'Immobilier',
    imageUrl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=400&h=300&fit=crop',
    isSponsored: false,
    createdAt: '30min',
    userName: 'Immobilière du Congo',
    isVerified: true,
    priceNegotiable: true,
  },
  {
    id: '6',
    title: 'Comptable senior — Cabinet Expertise Plus',
    price: 0,
    isFree: true,
    city: 'Brazzaville',
    neighborhood: 'Plateau',
    category: 'Emploi',
    imageUrl: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=400&h=300&fit=crop',
    isSponsored: false,
    createdAt: '1h',
    userName: 'Cabinet Expertise Plus',
    isVerified: true,
    priceNegotiable: false,
  },
  {
    id: '7',
    title: 'Robe de soirée wax — Taille M',
    price: 25000,
    city: 'Pointe-Noire',
    neighborhood: 'Loandjili',
    category: 'Mode & Beauté',
    imageUrl: 'https://images.unsplash.com/photo-1590735213920-68192a487bc2?w=400&h=300&fit=crop',
    isSponsored: false,
    createdAt: '4h',
    userName: 'Carine Moukoko',
    isVerified: false,
    priceNegotiable: true,
  },
  {
    id: '8',
    title: 'Groupe électrogène 6.5 KVA — HONDA',
    price: 450000,
    city: 'Dolisie',
    neighborhood: 'Centre',
    category: 'Électronique',
    imageUrl: 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=400&h=300&fit=crop',
    isSponsored: false,
    createdAt: '6h',
    userName: 'Serge Ngoubili',
    isVerified: true,
    priceNegotiable: true,
  },
  {
    id: '9',
    title: 'Plombier professionnel — Dépannage 24h/24',
    price: 15000,
    city: 'Brazzaville',
    neighborhood: 'Ouenzé',
    category: 'Services',
    imageUrl: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=400&h=300&fit=crop',
    isSponsored: false,
    createdAt: '2j',
    userName: 'Éric Makaya',
    isVerified: true,
    priceNegotiable: false,
  },
  {
    id: '10',
    title: 'Sacs de ciment DANGOTE — Livraison Brazza',
    price: 5500,
    city: 'Brazzaville',
    neighborhood: 'Talangaï',
    category: 'Matériaux BTP',
    imageUrl: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=400&h=300&fit=crop',
    isSponsored: false,
    createdAt: '8h',
    userName: 'Congo Matériaux',
    isVerified: true,
    priceNegotiable: true,
  },
  {
    id: '11',
    title: 'Perroquets gris du Gabon — Couple reproducteur',
    price: 120000,
    city: 'Ouesso',
    neighborhood: 'Centre',
    category: 'Animaux',
    imageUrl: 'https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=400&h=300&fit=crop',
    isSponsored: false,
    createdAt: '1j',
    userName: 'Marcel Ondongo',
    isVerified: false,
    priceNegotiable: true,
  },
  {
    id: '12',
    title: 'Guitare acoustique Yamaha F310 — Comme neuve',
    price: 95000,
    city: 'Brazzaville',
    neighborhood: 'Makélékélé',
    category: 'Loisirs',
    imageUrl: 'https://images.unsplash.com/photo-1510915361894-db8b60106cb1?w=400&h=300&fit=crop',
    isSponsored: false,
    createdAt: '12h',
    userName: 'Fiston Malonga',
    isVerified: false,
    priceNegotiable: false,
  },
];
